# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Justice Carcache Diaz
email: kevin.carcache@utp.ac.pa
description: > # this means to ignore newlines until "baseurl:"
  FullStack Developer, Ingeniero en Sistemas, Desarrollador de Videojuegos y
  Músico. Este es mi blog personal, en el cual intentaré mostrar los diferentes 
  proyectos en los cuales estoy trabajando.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karkadian.github.io" # the base hostname & protocol for your site
twitter_username: kjcd2518
github_username: karkadian

# Build settings
markdown: kramdown
