# SITE CONFIGURATION
baseurl: "/"
url: "http://karkadian.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Kevin Justice Carcache
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Mi blog personal" # used by search engines

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Programador FullStack y Desarrollador de videojuegos</p></br>
     <p>Un pequeño vistazo a los proyectos en los que he trabajado.</p>
  header_text_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Icons
  rss: false
  email_address: "kevin.carcache@utp.ac.pa" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "KJJCD2516"
  flickr:
  gitlab:
  github: "karkadian"
  google_plus:
  instagram:
  keybase:
  linkedin: "https://www.linkedin.com/in/kevin-carcache-26a09297/" # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "kjcd2518"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: true
  search: true
  tags: true


  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Siguiente post"
  str_previous_post: "Post anterior"
  str_next_page: "Siguiente"
  str_previous_page: "Anterior"
  str_continue_reading: "Continuar leyendo"
  str_javascript_required_disqus: "Por favor activa el javascript para ver los comentarios."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
